### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by praneybehl** [paveltyavin/bbslider#10]
Hi thanks for creating this library, especial with elessar not being maintained anymore.

My questions are:
1. Is there a way to disable the ghost?
2. Is there a way to add individual read-only ranges that are fixed and read-only.

Looking forward to possible solutions.
Cheers,
Praney

**Comment by paveltyavin** [comment]
Both ideas look very reasonable.

**Comment by paveltyavin** [comment]
@praneybehl, please check your features in 0.5.0

**Comment by praneybehl** [comment]
Wow superman speed, cheers. Checking it out 👍
