### ISSUE TITLE
Start from anywhere with "Step" option

### ISSUE THREAD

**Issue by Ne9ative** [paveltyavin/bbslider#13]
Hi, I want to start selecting every hours with "Step" option to 180(3hours), I've been looking for a way to do this, but I can't find any solution

My problem is if I have a 24-hour day For exemple I want to put slots of 3 hours, I can not choose when it start, its only 00:00 03:00 06:00 09:00 ... I would like to start selecting for example at 10:00 but impossible this way...

Maybe with "minWidth" but for resizing...?

Thanks

**Comment by paveltyavin** [comment]
sorry, but i didn't catch the idea. What's the problem if you specify either `minWidth` and `step` option?

**Comment by paveltyavin** [comment]
I've specified `minWidth`, `step` and `allowRemove` options here ,checkout: https://jsfiddle.net/x33bsw4u/1/

**Comment by Ne9ative** [comment]
Hi, thanks for reply
Sorry for my bad explanation 

ok so if my option is like this:
```
    min: 0, 
    max: 24,
    step: 3, // (3 hours)
```
	
The slider looks like this:
![img1](https://cloud.githubusercontent.com/assets/360624/24022857/23541720-0aa9-11e7-854d-36a54bdb5dc4.JPG)



But I try to do something like this:
```
	min: 0, 
	max: 24,
	step: 1, // (1 hours)
	rangeWidth: 3, // (3 hours) The magic option :D
```
![img2](https://cloud.githubusercontent.com/assets/360624/24023133/8e2960f4-0aaa-11e7-89c5-33dcbd0a2d4f.JPG)

This way I can start my slot of 3 hours every hours

**Comment by paveltyavin** [comment]
Ok, i've got it.

**Comment by Ne9ative** [comment]
So do you think we can do something about this or it's too complicated?
