### ISSUE TITLE
Intersection error when adding a range after one has been removed

### ISSUE THREAD

**Issue by jameshoward** [paveltyavin/bbslider#7]
If I add a range (e.g. 10–20) then remove it and attempt to add a new range that would intersect, I get an error `intersection`, even though there shouldn't be any overlap because the original range was removed.

(By the way, this is a great project, sorry for raising a few bugs but I'm really keen to use this on a project of mine because it's exactly what I need :))

**Comment by paveltyavin** [comment]
Hi. I was trying to reproduce the bug , but I didn't encounter with it . Can you make a jsfiddle for me?

**Comment by jameshoward** [comment]
Sorry, I don't seem to be able to recreate the issue so it must have been something I was doing wrong. I've since changed my code and now have no issues. Thanks for looking in to it and sorry to take your time.
