### ISSUE TITLE
How can I use the MultipleRangeSlider as an Angular Directive

### ISSUE THREAD

**Issue by ergodaveh** [paveltyavin/bbslider#8]
Thanks for providing the project .  Recently, I have had success using the jQuery Slider within Angular using the Directive,  as such using a resource found here  http://stackoverflow.com/questions/25550379/convert-jquery-ui-slider-widget-to-angularjs-directive
  Do you have any implementation for AngularJs?

Cheers,

**Comment by paveltyavin** [comment]
Hi. Sorry, I do not have any plugin for angular, nor for react/ember/etc. 
I would be glad, if you make some :)
